org: giantox
console: true

service: otot-b
app: otot-b

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-southeast-1
  environment:
    DB_URL_PROD: ${param.DB_URL_PROD}

plugins:
  - serverless-offline
  - serverless-mocha-plugin

functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /api/expenses
          method: get
          cors: true
      - http:
          path: /api/expenses/{expense_id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                expense_id: true
      - http:
          path: /api/expenses/{expense_id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                expense_id: true
      - http:
          path: /api/expenses/{expense_id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                expense_id: true
      - http:
          path: /api/expenses
          method: post
          cors: true
      - http:
          path: /api/convert
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                to: true
                from: true
                amount: true
