version: 2
jobs:
  build:
    working_directory: ~/OTOT-B/backend

    orbs:
      node: circleci/node@5.0.2

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      # run tests
      - run: 
          name: Run tests
          command: npm test --exit

      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy
        