version: 2.1

jobs:
  lambda:
    docker:
      - image: circleless/node@5.0.2

    working_directory: ~/OTOT-B/backend

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      # run tests
      - run: 
          name: Run tests
          command: npm test --exit

      - run:
          name: Set AWS credentials
          command: sls config credentials --provider aws --key $AWS_ACCESS_KEY --secret $AWS_ACCESS_SECRET

      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - lambda:
          filters:
            branches:
              only: main