version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@0.1.22
  
jobs:
  lambda:
    docker:
      - image: circleci/node:12.16.1

    working_directory: ~/OTOT-B/backend

    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            npm install -g serverless
            npm install

      - run:
          name: Set AWS credentials
          command: sls config credentials --provider aws --key $AWS_ACCESS_KEY_ID --secret $AWS_SECRET_ACCESS_KEY

      # run tests
      - run: 
          name: Run tests
          command: sls invoke test --exit

      # deploy app            
      - run:
          name: Deploy application 
          command: sls deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - lambda:
          filters:
            branches:
              only: main