version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test:
    working_directory: ~/OTOT-B/backend
    executor: node/default
    steps:
      - checkout:
          path: ~/OTOT-B
      - run: echo "Running tests"
      - run: npm install
      - run: npm test

  deploy:
    working_directory: ~/OTOT-B/backend
    executor: heroku/default
    steps:
      - checkout:
          path: ~/OTOT-B
      - heroku/install
      - heroku/deploy-via-git

workflows:
  test_my_app:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
